### PR TITLE
Integration with coqbot

### LINKED ISSUE #8: @coqbot could automatically run benchmarks
@coqbot is already following the pull request webhook and thus it is aware of every "labeling" event in particular.
When it sees the "needs: benchmarking" label, it could automatically run the bench, and when it finishes, it could post the results as a comment and remove the label.

Before implementing this, I'd like to understand better the future of the benchmark infrastructure. Is it going to stay on Jenkins or could we move it to GitLab CI somehow and kill Jenkins completely?

### LINKED ISSUE #84: Automatically populating commit fields?
Can we add a parameter that can be filled with the PR number, and if it's non-empty, then the `new_coq_repository`, `new_coq_commit`, `old_coq_repository`, and `old_coq_commit` get filled automatically according to the following script?
```bash
if [ ! -z "${pr_number}" ]; then
  RESPONSE="$(curl "https://api.github.com/repos/coq/coq/pulls/${pr_number}")"
  new_coq_repository="$(echo "${RESPONSE}" | jq -r '.head.repo.clone_url')"
  new_coq_commit="$(echo "${RESPONSE}" | jq -r '.head.sha')"
  old_coq_repository="$(echo "${RESPONSE}" | jq -r '.base.repo.clone_url')"
  old_coq_commit="$(echo "${RESPONSE}" | jq -r '.base.sha')"

  for val in "${new_coq_repository}" "${new_coq_commit}" "${old_coq_repository}" "${old_coq_commit}"; do
    if [ -z "$val" ] || [ "val" == "null" ]; then
      echo 'ERROR: Invalid Response:'
      echo "${RESPONSE}"
      echo "Info:"
      curl -i "https://api.github.com/repos/coq/coq/pulls/${pr_number}"
      exit 1
    fi
  done
fi
```

consider (`-r` is for `--raw-output`):
```
$ curl https://api.github.com/repos/coq/coq/pulls/12197 | jq -r '.number,.base.sha,.base.repo.clone_url,.head.sha,.head.repo.clone_url'
12197
62105448c40adfff86c9b191e6de2335839a7b37
https://github.com/coq/coq.git
3dbb4e68f853cb0414aaf234ba186ad5e22ad31f
https://github.com/JasonGross/coq.git
```

I think this would both make benches easier to set up, and would make progress towards https://github.com/coq/bot/issues/8

### PR DESCRIPTION
**Pull request by JasonGross**
Closes #84
Closes coq/bot#8

Before this can be merged, I need to add `coq_pr_number` and `coq_pr_comment_id` fields to [the parameterized build](https://ci.inria.fr/coq/view/opam/job/benchmark-part-of-the-branch/configure).  I'm waiting to do this until I get reviews on / indications of support for this PR.

@Zimmi48 please advise on how to talk to coqbot appropriately

For integration in the other direction (step 2 of https://github.com/coq/bot/issues/8#issuecomment-621530793), we need to check off "Trigger builds remotely (e.g., from scripts)" under ["Build Triggers"](https://ci.inria.fr/coq/view/opam/job/benchmark-part-of-the-branch/configure#section44), generate an "Authentication Token" and then have coqbot post(?) to `https://ci.inria.fr/coq/view/opam/job/benchmark-part-of-the-branch/buildWithParameters?token=$TOKEN&cause=coqbot&coq_pr_number=$PR_NUMBER&coq_pr_comment_id=$COMMENT_ID`, I believe.

### CODE REVIEW

File: two_points_on_the_same_branch.sh [hunk 1]
```diff
@@ -45,6 +54,49 @@ check_variable "old_coq_opam_archive_git_branch"
...
+        echo "DEBUG: new_coq_repository = $new_coq_repository"
+        echo "DEBUG: new_coq_commit = $new_coq_commit"
+        echo "DEBUG: old_coq_repository = $old_coq_repository"
+        echo "DEBUG: old_coq_commit = $old_coq_commit"
+    fi
+
+    # TODO: can we set the title automatically, rather than just echo this?
+    # e.g., cf https://ci.inria.fr/coq/cli/command/set-build-display-name,
+    # java -jar jenkins-cli.jar -s "${JENKINS_URL}" set-build-display-name "${JOB_NAME}" "${BUILD_NUMBER}" "PR #${coq_pr_number}: ${coq_pr_title}"
+    echo "Build for PR #${coq_pr_number}: ${coq_pr_title}"
```
Comment (JasonGross) [inline two_points_on_the_same_branch.sh]: Do we have access to the cli jar, or some way of doing this?

File: two_points_on_the_same_branch.sh [hunk 2]
```diff
@@ -119,6 +182,56 @@ if [ $(echo "$coq_opam_packages_on_separate_lines" | wc -l) != $(echo "$coq_opam
...
+            # XXX TODO Is this the right way to get the data out there?  Do we need to encode it?
+            curl -X POST --data-urlencode "${comment_text}" "${coqbot_url_prefix}/${coq_pr_number}/update-comment/${coq_pr_comment_id}"
+        elif [ ! -z "${is_done}" ]; then
+            # XXX TODO Is this the right way to get the data out there?  Do we need to encode it?
+            curl -X POST --data-urlencode "${comment_text}" "${coqbot_url_prefix}/${coq_pr_number}"
+        fi
+        if [ ! -z "${is_done}" ]; then
+            # XXX TODO FIXME How should we communicate this to coqbot?
+            curl -X POST "${coqbot_url_prefix}/${coq_pr_number}/benchmarking-done"
+        fi
```
Comment (JasonGross) [inline two_points_on_the_same_branch.sh]: @Zimmi48 How should we be indicating these things to coqbot?

File: two_points_on_the_same_branch.sh [hunk 3]
```diff
@@ -45,6 +54,49 @@ check_variable "old_coq_opam_archive_git_branch"
 check_variable "num_of_iterations"
 check_variable "coq_opam_packages"
 
+if which jq > /dev/null; then
```
Comment (JasonGross) [inline two_points_on_the_same_branch.sh:57]: Can someone with permissions please install `jq` on pendulum?

File: two_points_on_the_same_branch.sh (hunk 2 above)
Comment (Zimmi48) [reply two_points_on_the_same_branch.sh]: I'd prefer to keep using static endpoints and put any additional information in the body of the request.

File: two_points_on_the_same_branch.sh (hunk 3 above)
Comment (gares) [reply two_points_on_the_same_branch.sh:57]: CC @maximedenes

File: two_points_on_the_same_branch.sh (hunk 2 above)
Comment (JasonGross) [reply two_points_on_the_same_branch.sh]: What should I put into the body to indicate this?

Comment (Zimmi48) [reply two_points_on_the_same_branch.sh]: I am not sure I understood correctly your question. But the URL should be something static, like `/benchmarking-done` and the body should contain the information you need to pass to @coqbot. This could be the PR number on the first line, then the content to copy into the PR on the following lines. Anything that can be parsed easily is fine. JSON would be OK as well but it's probably not a good idea to generate JSON without a specialized tool.

Comment (JasonGross) [reply two_points_on_the_same_branch.sh]: @Zimmi48 I've updated the urls to be static (I've used `/update-comment`, `/new-comment`, and `/benchmarking-done` to indicate that the `needs: benchmarking` label should be removed (there's a question of how to handle cases where the bench dies in the middle; do we want to leave `needs: benchmarking` in those cases, or do we want it removed when the bench is queued?)  I'm currently having the text be url-encoded, so I think you can just split on `&` and then split each entry on the first `=` and then url-un-encode the contents.

File: two_points_on_the_same_branch.sh (hunk 3 above)
Comment (ppedrot) [reply two_points_on_the_same_branch.sh:57]: Done.

Comment (JasonGross) [reply two_points_on_the_same_branch.sh:57]: Thanks!

**Comment by JasonGross** [comment]
Now that pendulum has jq, should we merge this?  I've updated the build configuration, so I think merging this won't break anything.  Then someone needs to write the coqbot infrastructure to deal with this.

File: two_points_on_the_same_branch.sh [hunk 4]
```diff
@@ -55,6 +73,45 @@ else
...
+                                   # automatically computing values
+        echo "DEBUG: new_coq_repository = $new_coq_repository"
+        echo "DEBUG: new_coq_commit = $new_coq_commit"
+        echo "DEBUG: old_coq_repository = $old_coq_repository"
+        echo "DEBUG: old_coq_commit = $old_coq_commit"
+    fi
+
+    # cf https://wiki.jenkins.io/display/JENKINS/Jenkins+CLI
+    # TODO: Is there a better place to put the cli?  Is it already available somewhere?
+    curl "${JENKINS_URL}/jnlpJars/jenkins-cli.jar" -o "$working_dir/jenkins-cli.jar"
```
Comment (JasonGross) [inline two_points_on_the_same_branch.sh:114]: @maximedenes Is this (https://ci.inria.fr/coq/jnlpJars/jenkins-cli.jar) the same as the one that you pointed at that's at /home/jenkins/jenkins-slave/slave.jar

File: two_points_on_the_same_branch.sh (hunk 2 above)
Comment (Zimmi48) [reply two_points_on_the_same_branch.sh]: > I'm currently having the text be url-encoded, so I think you can just split on `&` and then split each entry on the first `=` and then url-un-encode the contents.

Hum, more work for me then.

Comment (JasonGross) [reply two_points_on_the_same_branch.sh]: Feel free to suggest any other encoding that supports newlines, etc.  This was the most common one that I saw used on the internet.  If you just want the text raw, separated by newlines, I can also make it do that.

Comment (Zimmi48) [reply two_points_on_the_same_branch.sh]: Yep, I prefer to have the data in the either JSON format, or raw and newline separated.

Comment (JasonGross) [reply two_points_on_the_same_branch.sh]: @Zimmi48 I've updated it to use
```bash
# Tell coqbot to update the in-progress comment
curl -X POST --data-binary "${coq_pr_number}${nl}${coq_pr_comment_id}${nl}${comment_text}" "${coqbot_url_prefix}/update-comment"
```
```bash
# Tell coqbot to post a new comment that we're done benchmarking
curl -X POST --data-binary "${coq_pr_number}${nl}${comment_text}" "${coqbot_url_prefix}/new-comment"
```
and
```bash
# Tell coqbot to remove the `needs: benchmarking` label
curl -X POST --data-binary "${coq_pr_number}" "${coqbot_url_prefix}/benchmarking-done"
```
Does this work?

**Comment by JasonGross** [comment]
@ejgallego Can you review/approve/merge this?  (Or give me permissions?)  I believe it's ready for merge.

**Comment by ejgallego** [comment]
> @ejgallego Can you review/approve/merge this? (Or give me permissions?) I believe it's ready for merge.

@JasonGross I gave you permission [in a kind of hacky way, I need to work more on the setup]

Anyways I'll merge myself as not to delay this more, thanks for the work!

**Review by ejgallego — APPROVED** [review]
LGTM thanks.
